### ISSUE TITLE
While using LDAP connection only in providers.json, get the errors below

### ISSUE THREAD

**Issue by DanielChuDC** [strongloop/loopback-example-passport#116]
# Environment
`node -v`
v10.15.3
`npm -v`
6.10.1

# Description/Steps to reproduce
```
{
  "ldap": {
    "provider": "ldap",
    "authScheme": "ldap",
    "module": "passport-ldapauth",
    "authPath": "/auth/ldap",
    "successRedirect": "/auth/account",
    "failureRedirect": "/ldap",
    "session": true,
    "failureFlash": true,
    "profileAttributesFromLDAP": {
      "login": "uid",
      "username": "uid",
      "displayName": "displayName",
      "email": "uid",
      "externalId": "uid"
    },
    "server": {
      "url": "ldap://serverip:1234",
      "searchBase": "dc=blah,dc=blah",
      "searchFilter": "({{username}})"
    }
  }
}
```

Run the project with `node .`

# Expected result
The program will run at localhost:3000 or localhost:3000/explorer.

# Real result
 Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/loopback-example-passport/node_modules/ldapjs/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /loopback-example-passport/node_modules/ldapjs/lib/dtrace.js:84:20
    at Object.<anonymous> (/loopback-example-passport/node_modules/ldapjs/lib/dtrace.js:124:2)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) code: 'MODULE_NOT_FOUND' }

**Comment by dhmlau** [comment]
@DanielChuDC, responding to [your other issue ](https://github.com/strongloop/loopback-example-passport/issues/117), are you using LoopBack 3 or LoopBack 4? 
Please refer to our recent blog on the authentication module updates in LoopBack 4: https://strongloop.com/strongblog/loopback-4-authentication-updates/. Thanks.

**Comment by DanielChuDC** [comment]
Ok thanks for the reply. I am just running the project by issue command 'node .' in my terminal.
But the project is not running. Just wonder which part is missing.

Anyway, thanks for pointing me to the direction for Loopback4 as I am implement loopback 4 authentication.

I think can close this issue.
