### ISSUE TITLE
The model type must be a constructor

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-example-passport#25]
I'm trying to use the example code in this app in mine, but am running into this error

```server-0 (err): AssertionError: The model type must be a constructor
server-0 (err):     at Function.registry.getModelByType (/usr/local/lib/node_modules/loopback/lib/registry.js:286:3)
server-0 (err):     at PassportConfigurator.setupModels (/usr/local/lib/node_modules/loopback-component-passport/lib/passport-configurator.js:33:70)
server-0 (err):     at Object.<anonymous> (/opt/nodegloo/server/server.js:71:22)
server-0 (err):     at Module._compile (module.js:456:26)
server-0 (err):     at Object.Module._extensions..js (module.js:474:10)
server-0 (err):     at Module.load (module.js:356:32)
server-0 (err):     at Function.Module._load (module.js:312:12)
server-0 (err):     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:187:23```

this is in the passportConfigurator.setupModels() function

 it seems when this is being called, app.models.user / userIdentity / userCredential are undefined and therefore causing the problem

Am I missing something, or is there a bug / mistake / setup problem ?

thanks

**Comment by jmls** [comment]
found the problem

my model-config.json was missing the line

"./node_modules/loopback-component-passport/lib/models"

**Comment by a-reda** [comment]
Hello, 

I tried your solution but still not working, any other suggestion? 

Thanks,

**Comment by brunocascio** [comment]
same problem

**Comment by a-reda** [comment]
I solved it by adding in model-config.json because I frogot them
' ' '
 "accessToken": {
    "dataSource": "db",
    "public": true
  },
  "userCredential": {
    "dataSource": "db",
    "public": true
  },
  "userIdentity": {
    "dataSource": "db",
    "public": true
  }
' ' '

**Comment by brunocascio** [comment]
Thanks, works!

note: Use  `UserCredential`and `UserIdentity` instead of `userCredential`and `userIdentity`

**Comment by johannesjo** [comment]
Same error here and none of the solutions work for me. The models are undefined at the moment of time theyre accessed.

**Comment by johannesjo** [comment]
Turns out that I need to boot the app before the models can be accessed.

**Comment by reflog** [comment]
@johannesjo solution works. place the code after the boot.

**Comment by swapnilg** [comment]
yes thanks @johannesjo

**Comment by superkhau** [comment]
Looks like you guys managed to solve this one. Can I close this @jmls?

**Comment by superkhau** [comment]
Closing due to inactivity. I will reopen it if you guys are still running into issues.

**Comment by romainquellec** [comment]
Thanks, works!

note: Use UserCredential and UserIdentity instead of userCredential and userIdentity

else, model not found.

=> Is that fine to use the same name UserCredential and UserIdentity with first capital ?

**Comment by s-thornton** [comment]
I'm still having issues with this...I've tried all of the mentioned solutions except for @johannesjo solution.  I'm not sure that I understand what he means by "The models are undefined at the moment of time theyre accessed." and "Turns out that I need to boot the app before the models can be accessed."  Is this referring to booting your strongloop application (i.e. slc start appName)?  I am new to strongloop and passport.  I've been referencing this https://github.com/strongloop/loopback-example-passport to get started.

I'm sure it's just user error, but any help would be appreciated.

Thanks

**Comment by lwhiteley** [comment]
please be aware of your folder structure
because the model-config is in the server folder then the sources path should be
`"../node_modules/loopback-component-passport/lib/models"`

which is one directory back

**Comment by Jcbobo88** [comment]
i i have to change the server.js file created with the generator,  changing 

`boot(app, __dirname, function(err) {
  if (err) throw err;

  // start the server if `$ node server.js`
  if (require.main === module)
    app.start();
});`

to `
boot(app, __dirname);
`
inserting the passportConfigurator setModels inside the callback functions was not working (i really don't know why).

**Comment by totymedli** [comment]
For me I had to do all the suggestions @jmls, @a-reda, @brunocascio and @johannesjo gave. So here is an overall:

1. Add `"./node_modules/loopback-component-passport/lib/models"` to `server/model-config.json`'s `_meta.sources` array.
2. Add the following models to the same file (with PascalCase model names in case of LoopBack v3)
    ```
    "AccessToken": {
      "dataSource": "db",
      "public": true
    },
    "UserCredential": {
      "dataSource": "db",
      "public": true
    },
    "UserIdentity": {
      "dataSource": "db",
      "public": true
    },
    ```
3. Call `boot()` from `loopback-boot` before `passportConfigurator.setupModels` because models in `app.models` are only available after boot.

**Comment by arifsohail** [comment]
structure of you server.js file should be like this as mentioned by @johannesjo 
```app.start = function() {
  // start the web server
  return app.listen(() => {
    if (app.get('loopback-component-explorer')) {
    }
  });
};

boot(app, __dirname, (err) => {
  if (err) throw err;
  // start the server if `$ node server.js`
  if (require.main === module) {
    app.start();
  }
});
// Set up related models
passportConfigurator.setupModels({
  userModel: app.models.account,
  userIdentityModel: app.models.userIdentity,
  userCredentialModel: app.models.userCredential
});
// Configure passport strategies for third party auth providers
for(var s in config) {
  var c = config[s];
  c.session = c.session !== false;
  passportConfigurator.configureProvider(s, c);
}```
