### ISSUE TITLE
Page 'pages/linkedAccounts' missing from sample

### ISSUE THREAD

**Issue by danifitz** [strongloop/loopback-example-passport#69]
In `server/server.js` there is a method

    app.get('/link/account', ensureLoggedIn('/login'), function (req, res, next) {
      res.render('pages/linkedAccounts', {
        user: req.user,
        url: req.url
      });
    });

which refers to 'pages/linkedAccounts'. This page doesn't exist in `server/views/pages`.

When you click 'Link with Facebook/Google' button on the accounts page you get the following error:

`Error: Failed to lookup view "pages/linkedAccounts" in views directory "/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/server/views"
    at EventEmitter.render (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/loopback/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/loopback/node_modules/express/lib/response.js:961:7)
    at ServerResponse.res.render (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/express-flash/lib/express-flash.js:29:16)
    at /Users/danielfitzgerald/Documents/workspace/loopback-example-passport/server/server.js:97:7
    at Layer.handle [as handle_request] (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/loopback/node_modules/express/lib/router/route.js:131:13)
    at /Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/connect-ensure-login/lib/ensureLoggedIn.js:50:5
    at Layer.handle [as handle_request] (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/loopback/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/danielfitzgerald/Documents/workspace/loopback-example-passport/node_modules/loopback/node_modules/express/lib/router/route.js:112:3)`

**Comment by jannyHou** [comment]
hey @danifitz you are right, `pages/linkedAccounts` is no longer valid we move same things to `pages/loginProfiles`

And I cannot reproduce your problem when clicking "Link with Facebook/Google", did you do configuration in `provider.json` file?
Please follow the guide here to run this demo:
https://github.com/strongloop/loopback-example-passport/blob/master/README.md

Hope this could help you!
